// <auto-generated />
using System;
using ArtemisBankingPro.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtemisBankingPro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    partial class BankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("BankingNumberSequence")
                .HasMin(1L)
                .HasMax(999999999L);

            modelBuilder.Entity("ArtemisBankingPro.Application.Interfaces.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResultReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationType");

                    b.HasIndex("IdempotencyKey", "ActorId")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", "dbo");
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Accounts.Beneficiaries.Entities.Beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DestinationAccountId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OwnerUserId", "DestinationAccountId")
                        .IsUnique();

                    b.ToTable("Beneficiaries", "dbo");
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Accounts.Entities.AccountTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BeneficiaryReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid>("FinancialOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("FinancialOperationId");

                    b.ToTable("AccountTransactions", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_AccountTransactions_Amount_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Accounts.Entities.SavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OwnerUserId", "Type")
                        .IsUnique()
                        .HasFilter("[Type] = 1");

                    b.ToTable("SavingsAccounts", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_SavingsAccounts_Balance_NonNegative", "[Balance] >= 0");

                            t.HasCheckConstraint("CK_SavingsAccounts_Number_NineDigits", "LEN([Number]) = 9 AND [Number] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Cards.Entities.CardConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<Guid>("FinancialOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MerchantDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("FinancialOperationId")
                        .IsUnique();

                    b.HasIndex("MerchantId");

                    b.ToTable("CardConsumptions", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_CardConsumptions_Amount_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Cards.Entities.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CvcDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PanFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("PanFingerprint")
                        .IsUnique();

                    b.ToTable("CreditCards", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_CreditCards_Debt_NonNegative", "[CurrentDebt] >= 0");

                            t.HasCheckConstraint("CK_CreditCards_Debt_Within_Limit", "[CurrentDebt] <= [CreditLimit]");

                            t.HasCheckConstraint("CK_CreditCards_Fingerprint_Hex", "LEN([PanFingerprint]) = 64 AND [PanFingerprint] NOT LIKE '%[^0-9A-Fa-f]%'");

                            t.HasCheckConstraint("CK_CreditCards_LastFour_Digits", "[LastFour] LIKE '[0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_CreditCards_Limit_Positive", "[CreditLimit] > 0");
                        });
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Lending.Entities.Installment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("bit");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("ScheduledAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LoanId", "DueDate");

                    b.HasIndex("LoanId", "Number")
                        .IsUnique();

                    b.ToTable("Installments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Installments_Paid_NonNegative", "[PaidAmount] >= 0");

                            t.HasCheckConstraint("CK_Installments_Paid_Within_Scheduled", "[PaidAmount] <= [ScheduledAmount]");

                            t.HasCheckConstraint("CK_Installments_Scheduled_NonNegative", "[ScheduledAmount] >= 0");
                        });
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Lending.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("ApprovedPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Loans", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Loans_Number_NineDigits", "LEN([Number]) = 9 AND [Number] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Loans_Principal_Positive", "[ApprovedPrincipal] > 0");

                            t.HasCheckConstraint("CK_Loans_Term_Allowed", "[TermMonths] IN (6, 12, 18, 24, 30, 36, 42, 48, 54, 60)");
                        });
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Merchants.Entities.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedUserId")
                        .IsUnique()
                        .HasFilter("[AssociatedUserId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Rnc")
                        .IsUnique();

                    b.ToTable("Merchants", "dbo");
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Operations.Entities.FinancialOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LoanNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("LoanNumber");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Kind", "Status");

                    b.ToTable("FinancialOperations", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_FinancialOperations_Applied_NonNegative", "[AppliedAmount] >= 0");

                            t.HasCheckConstraint("CK_FinancialOperations_Interest_NonNegative", "[InterestAmount] >= 0");

                            t.HasCheckConstraint("CK_FinancialOperations_Requested_Positive", "[RequestedAmount] > 0");
                        });
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Accounts.Beneficiaries.Entities.Beneficiary", b =>
                {
                    b.HasOne("ArtemisBankingPro.Domain.Accounts.Entities.SavingsAccount", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Accounts.Entities.AccountTransaction", b =>
                {
                    b.HasOne("ArtemisBankingPro.Domain.Operations.Entities.FinancialOperation", null)
                        .WithMany("AccountTransactions")
                        .HasForeignKey("FinancialOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Cards.Entities.CardConsumption", b =>
                {
                    b.HasOne("ArtemisBankingPro.Domain.Cards.Entities.CreditCard", null)
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtemisBankingPro.Domain.Operations.Entities.FinancialOperation", null)
                        .WithOne("CardConsumption")
                        .HasForeignKey("ArtemisBankingPro.Domain.Cards.Entities.CardConsumption", "FinancialOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtemisBankingPro.Domain.Merchants.Entities.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Cards.Entities.CreditCard", b =>
                {
                    b.OwnsOne("ArtemisBankingPro.Domain.Cards.ValueObjects.CardExpiration", "Expiration", b1 =>
                        {
                            b1.Property<int>("CreditCardId")
                                .HasColumnType("int");

                            b1.Property<int>("Month")
                                .HasColumnType("int")
                                .HasColumnName("ExpirationMonth");

                            b1.Property<int>("Year")
                                .HasColumnType("int")
                                .HasColumnName("ExpirationYear");

                            b1.HasKey("CreditCardId");

                            b1.ToTable("CreditCards", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("CreditCardId");
                        });

                    b.Navigation("Expiration")
                        .IsRequired();
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Lending.Entities.Installment", b =>
                {
                    b.HasOne("ArtemisBankingPro.Domain.Lending.Entities.Loan", null)
                        .WithMany("Installments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Lending.Entities.Loan", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("ArtemisBankingPro.Domain.Operations.Entities.FinancialOperation", b =>
                {
                    b.Navigation("AccountTransactions");

                    b.Navigation("CardConsumption");
                });
#pragma warning restore 612, 618
        }
    }
}
