<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\ArtemisBankingPro.Application\ArtemisBankingPro.Application.csproj" />
    <ProjectReference Include="..\..\Core\ArtemisBankingPro.Domain\ArtemisBankingPro.Domain.csproj" />
  </ItemGroup>

</Project>
